use correct memberdata-property
login_form worked on plone4.3.9, but on plone 4.3.11 we got a ValueError when logging in.

```
ValueError: The property enable_two_factor_authentication does not exist
```

The authentication code got sent via SMS, but validation resulted in a
"Invalid token or token expired" message.